### ISSUE TITLE
Double-check color contrasts

### ISSUE THREAD

**Issue by nhistory** [DaleStudy/leetcode-website#156]
현재 디스코드 참여하기 버튼 백그라운드 컬러와 폰트 컬러 사이 컨트라스트 대비가 접근성 기준에 부합하지 않음

![Image](https://github.com/user-attachments/assets/d0dcd03e-8a2c-40bf-9737-65851d6b9706)

**Comment by nhistory** [comment]
해결방안

- 버튼 백그라운드용 컬러를 추가해서 변경



![Image](https://github.com/user-attachments/assets/6af65f74-64c0-4d1f-8795-84c971d2cab8)

-> WCAG의 모든 색상대비 기준을 만족함


![Image](https://github.com/user-attachments/assets/acf17ee1-d457-412f-9045-aff4336466d8)

-> 이에 따라 버튼 hover 에서의 색상도 변경이 필요함. (피그마 프로젝트에서 확인 가능)


![Image](https://github.com/user-attachments/assets/8b61ff01-c95c-4d32-82fe-18d8bd28bfc5)

@sounmind 위 변경사항에 따라 코드 변경이 필요한데요. 티켓을 새로 만들어야 할까요?

**Comment by sounmind** [comment]
@nhistory 아뇨 여기서 바로 해결하면 될 것 같습니다ㅎㅎ

**Comment by sounmind** [comment]
@nhistory 그리고 Figma의 css variable들을 현재 글로벌 스타일에 있는 네이밍대로 변경해주실 수 있을까요?
```css
:root {
  --primary: #846de9;
  --secondary: #24eaca;
  --bg-100: #fdfdff;
  --bg-200: #fbfaff;
  --bg-300: #eee8fe;
  --btn-background: #5333E1
  --text-900: #160b46;
  --font-weight-light: 300;
  --font-weight-regular: 400;
  --font-weight-medium: 500;
  --font-weight-bold: 700;
}
```
