### ISSUE TITLE
Implement CSS transition for all elements hover effect

### ISSUE THREAD

**Issue by SamTheKorean** [DaleStudy/leetcode-website#162]
Mouse hover 동작 시 모든 엘리먼트에서 transition 200ms가 반영되었으면 좋겠습니다.

Global style로 적용한다 vs 각각 엘리먼트마다 적용한다

Global style로 결정

**Comment by yolophg** [comment]
* step.js에 선적용되어있는 StepTextLink 클래스 내 transition도 삭제 부탁드립니다!
```css
      a:hover {
        font-weight: var(--font-weight-bold);
        text-decoration: underline 3px;
        transition: 200ms;
      }
```
